exclude:
  - "TOI*"
  - "data*"
  - "*_temp"
  - "*.pkl"
  - "*.fits"
  - "docs/"
  - "generate_figures.py"
  - "template_nointerp.py"
  - "gaussian_savgol.py"
  - "plot_sp.py"
  - "template_nointerp.py"
  - "requirements.txt"
  - "pyproject.toml"
